package strategies

import (
	"time"

	"forex-trading-sim/internal/models"
)

// Signal represents a trading signal generated by a strategy
type Signal struct {
	Type       SignalType   // BUY, SELL, HOLD
	Strength   float64      // 0-100 confidence
	Price      float64      // Entry price suggestion
	StopLoss   float64      // Stop loss price
	TakeProfit float64      // Take profit price
	Reason     string       // Description of why signal was generated
	Timestamp  time.Time    // When signal was generated
}

// SignalType represents the type of trading signal
type SignalType string

const (
	SignalBuy  SignalType = "BUY"
	SignalSell SignalType = "SELL"
	SignalHold SignalType = "HOLD"
)

// Order represents a trade order
type Order struct {
	Type          OrderType   // MARKET, LIMIT, STOP
	Side          SignalType  // BUY, SELL
	Quantity      float64     // Lot size
	EntryPrice    float64     // Entry price
	StopLoss      float64     // Stop loss price
	TakeProfit    float64     // Take profit price
	Timeframe     string      // Timeframe (1m, 5m, 15m, 1h, 4h, 1d)
	CurrencyPair  string      // Currency pair symbol
	Timestamp     time.Time   // Order timestamp
}

// OrderType represents the type of order
type OrderType string

const (
	OrderMarket OrderType = "MARKET"
	OrderLimit  OrderType = "LIMIT"
	OrderStop   OrderType = "STOP"
)

// Portfolio represents the current portfolio state during backtesting
type Portfolio struct {
	Equity         float64            // Current equity
	Cash           float64            // Available cash
	OpenPositions  []Position         // Currently open positions
	ClosedTrades  []BacktestTrade    // Closed trades history
}

// Position represents an open position in the portfolio
type Position struct {
	ID             string    // Unique position ID
	Type           SignalType // BUY or SELL
	EntryPrice     float64   // Entry price
	Quantity       float64   // Position size
	StopLoss       float64   // Stop loss
	TakeProfit     float64   // Take profit
	OpenedAt       time.Time // When position was opened
	CurrencyPair   string    // Currency pair
}

// BacktestTrade represents a closed trade in backtest results
type BacktestTrade struct {
	ID             string     // Trade ID
	Type           SignalType // BUY or SELL
	EntryPrice     float64    // Entry price
	ExitPrice      float64    // Exit price
	Quantity       float64    // Trade size
	PnL            float64    // Profit/Loss
	PnLPercent     float64    // P&L percentage
	Commission     float64    // Commission paid
	Swap           float64    // Overnight swap
	EntryTime      time.Time  // Entry timestamp
	ExitTime       time.Time  // Exit timestamp
	StopLoss       float64    // Stop loss level
	TakeProfit     float64    // Take profit level
	Strategy       string     // Strategy name
	CurrencyPair   string     // Currency pair
}

// BarData represents OHLCV data for analysis
type BarData struct {
	Open       float64
	High       float64
	Low        float64
	Close      float64
	Volume     float64
	Timestamp  time.Time
}

// Strategy is the interface that all trading strategies must implement
type Strategy interface {
	// OnBar is called on each new bar - main logic for generating signals
	OnBar(bar BarData, history []BarData, portfolio Portfolio) Signal

	// OnSignal is called when a signal needs to be converted to an order
	OnSignal(signal Signal, portfolio Portfolio) *Order

	// OnTrade is called when a trade is executed
	OnTrade(trade BacktestTrade, portfolio *Portfolio)

	// GetParameters returns the strategy parameters
	GetParameters() map[string]interface{}

	// GetName returns the strategy name
	GetName() string

	// GetDescription returns the strategy description
	GetDescription() string

	// ValidateParameters validates the strategy parameters
	ValidateParameters() error
}

// BaseStrategy provides common functionality for all strategies
type BaseStrategy struct {
	Name        string
	Description string
	Parameters  map[string]interface{}
}

// GetParameters returns the strategy parameters
func (b *BaseStrategy) GetParameters() map[string]interface{} {
	return b.Parameters
}

// GetName returns the strategy name
func (b *BaseStrategy) GetName() string {
	return b.Name
}

// GetDescription returns the strategy description
func (b *BaseStrategy) GetDescription() string {
	return b.Description
}

// StrategyFactory creates strategy instances based on name
type StrategyFactory func(params map[string]interface{}) (Strategy, error)

// strategyRegistry holds all registered strategies
var strategyRegistry = make(map[string]StrategyFactory)

// RegisterStrategy registers a new strategy
func RegisterStrategy(name string, factory StrategyFactory) {
	strategyRegistry[name] = factory
}

// CreateStrategy creates a strategy instance by name
func CreateStrategy(name string, params map[string]interface{}) (Strategy, error) {
	factory, exists := strategyRegistry[name]
	if !exists {
		return nil, ErrStrategyNotFound{name}
	}
	return factory(params)
}

// ListStrategies returns list of all registered strategy names
func ListStrategies() []string {
	names := make([]string, 0, len(strategyRegistry))
	for name := range strategyRegistry {
		names = append(names, name)
	}
	return names
}

// ErrStrategyNotFound is returned when a strategy is not found
type ErrStrategyNotFound struct {
	Name string
}

func (e ErrStrategyNotFound) Error() string {
	return "strategy not found: " + e.Name
}

// Helper functions

// CalculatePositionSize calculates position size based on risk percentage
func CalculatePositionSize(equity, riskPercent, entryPrice, stopLoss float64) float64 {
	if entryPrice <= 0 || stopLoss <= 0 || equity <= 0 {
		return 0
	}
	riskAmount := equity * (riskPercent / 100)
	priceRisk := abs(entryPrice - stopLoss)
	if priceRisk == 0 {
		return 0
	}
	return riskAmount / priceRisk
}

// CalculateStopLoss calculates stop loss distance in pips
func CalculateStopLoss(entryPrice, stopLoss float64, isBuy bool) float64 {
	if isBuy {
		return entryPrice - stopLoss
	}
	return stopLoss - entryPrice
}

// CalculateTakeProfit calculates take profit distance in pips
func CalculateTakeProfit(entryPrice, takeProfit float64, isBuy bool) float64 {
	if isBuy {
		return takeProfit - entryPrice
	}
	return entryPrice - takeProfit
}

// abs returns absolute value
func abs(v float64) float64 {
	if v < 0 {
		return -v
	}
	return v
}

// ConvertBarData converts models.HistoricalPrice to BarData
func ConvertBarData(hp models.HistoricalPrice) BarData {
	return BarData{
		Open:      hp.Open,
		High:      hp.High,
		Low:       hp.Low,
		Close:     hp.Close,
		Volume:    hp.Volume,
		Timestamp: hp.Timestamp,
	}
}

// ConvertBarDataSlice converts multiple HistoricalPrice to BarData
func ConvertBarDataSlice(historicalPrices []models.HistoricalPrice) []BarData {
	bars := make([]BarData, len(historicalPrices))
	for i, hp := range historicalPrices {
		bars[i] = ConvertBarData(hp)
	}
	return bars
}
